name: CI/CD multi-project

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Deploy 3 Apps to Server via SSH
      env:
        DEPLOY_SERVER: ${{ secrets.DEPLOY_SERVER_IP }}
        DEPLOY_USER: ${{ secrets.DEPLOY_USER_UBUNTU }}
        SSH_KEY: ${{ secrets.SSH_KEY_UBUNTU }}
        
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -t rsa $DEPLOY_SERVER >> ~/.ssh/known_hosts
        echo "$SSH_KEY" | tr -d '\r' > temp_key
        chmod 600 temp_key

        ssh -i temp_key $DEPLOY_USER@$DEPLOY_SERVER << 'EOF'
          cd ~

          # Ganti ke multi-project sesuai nama folder kamu
          if [ ! -d "multi-project" ]; then
            git clone https://github.com/DioSptra/multi-project.git multi-project
          fi

          cd multi-project || exit 1
          git pull origin master

          # Install Docker if not installed
          if ! command -v docker &> /dev/null; then
            echo "Docker not found, installing..."
            bash install-docker.sh
          fi

          # ============ MINI GOJEK (Python) ============
          cd mini-gojek
          sudo docker stop mini-gojek || true
          sudo docker rm mini-gojek || true
          sudo docker build -t mini-gojek .
          sudo docker run -d --restart always --name mini-gojek -p 5000:5000 mini-gojek
          cd ..

          # ============ HABIT TRACKER (Node.js) ============
          cd habit-tracker || { echo "habit-tracker folder not found"; exit 1; }
          sudo docker stop habit-tracker || true
          sudo docker rm habit-tracker || true
          sudo docker build -t habit-tracker .
          sudo docker run -d --restart always --name habit-tracker -p 3000:3000 habit-tracker
          cd ..

          # ============  CONTACT BOOK (PHP) ============
          cd contact-book || { echo "contact-book folder not found"; exit 1; }
          sudo docker stop contact-book || true
          sudo docker rm contact-book || true
          sudo docker build -t contact-book .
          sudo docker run -d --restart always --name contact-book -p 8080:80 contact-book
          cd ..
        EOF
